apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pr-placeholder

resources:
- ingress.yaml
- resourcequota.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
  target:
    kind: Deployment

configMapGenerator:
- name: pr-metadata
  literals:
  - PR_NUMBER=placeholder
  - PR_BRANCH=placeholder
  - ENVIRONMENT=preview
